import gov.ca.cwds.cans.domain.entity.Assessment
import gov.ca.cwds.security.realm.PerryAccount

global Boolean authorizationResult

rule "Assessment in the same county"
  dialect "mvel"
  agenda-group "assessment-authorization-rules"
  when
      $assessment : Assessment($county : county)
      $user : PerryAccount(countyName.equalsIgnoreCase($county.name))
  then
      kcontext.getKieRuntime().setGlobal("authorizationResult", true);
end
