applicationName: "CWDS CANS API"
version: ${APP_VERSION:-local}

server:
  applicationConnectors:
  - type: http
    port: 8080
  - type: https
    port: 8443
    keyStorePath: ${KEY_STORE_FILE:-./config/testKeyStore.jks}
    keyStorePassword: ${KEY_STORE_PASSWORD:-testPass}
    keyStoreType: JKS
    supportedProtocols: [TLSv1, TLSv1.1, TLSv1.2]
  adminConnectors:
  - type: http
    port: 9081
  requestLog:
    appenders:
      - type: console

shiro:
  iniConfigs: ["file:${SHIRO_CONFIG_PATH:-config/shiro_v2.ini}"]
security:
  authorizationEnabled: ${AUTHORIZATION_ENABLED:-true}

swagger:
  templateName: /gov/ca/cwds/rest/views/swagger.mustache
  assetsPath: /static
  resourcePackage: gov.ca.cwds.cans.rest
  title: "CWDS CANS API"
  description: "RESTful CANS API."
  logo: images/CWDS-API-Logo-Horizontal.png
  loginUrl: ${LOGIN_URL:-http://localhost:18080/perry/authn/login}
  logoutUrl: ${LOGOUT_URL:-http://localhost:18080/perry/authn/logout}
  tokenUrl: ${SWAGGER_TOKEN_URL:-http://localhost:18080/perry/authn/token}
  showSwagger: ${SHOW_SWAGGER:-true}
  jsonUrl: ${SWAGGER_JSON_URL:-http://localhost:8080/swagger.json}
  callbackUrl: ${SWAGGER_CALLBACK_URL:-http://localhost:8080/swagger}

cansDataSourceFactory:
  driverClass: org.postgresql.Driver
  user: ${DB_NS_USER:-postgres_data}
  password: ${DB_NS_PASSWORD:-postgres_data}
  url: ${DB_NS_JDBC_URL:-jdbc:postgresql://localhost:5432/postgres_data}
  validationQuery: "select 1"
  logValidationErrors: true
  initialSize: 0
  minSize: 0
  maxSize: ${DB_NS_CP_MAX_SIZE:-8}
  minIdleTime: 1 minute
  properties:
      hibernate.dialect: gov.ca.cwds.cans.dao.hibernate.JsonbSupportPostgreSQL9Dialect
      hibernate.id.new_generator_mappings: false
      hibernate.show_sql: false
      hibernate.default_schema: ${DB_NS_SCHEMA:-cans}
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      hibernate.cache.use_query_cache: true

upgradeCansDbOnStart: ${UPGRADE_CANS_DB_ON_START:-false}
populateDemoDataOnStart: ${POPULATE_DEMO_DATA_ON_START:-true}

webSecurity:
  httpResponseSecurityHeaders:
    # Prevent MIMI sniffing
    X-Content-Type-Options: nosniff

    # Prevent click-jacking
    X-Frame-Options: deny

    # Prevent cross site scripting
    X-XSS-Protection: 1; mode=block

    # Prevent everything other than same origin
    Content-Security-Policy: default-src 'self' 'unsafe-inline';

logging:
  level: ${LOGLEVEL:-INFO}
  loggers:
    "org.hibernate.SQL":
      level: DEBUG
    "org.hibernate.type.descriptor.sql":
      level: DEBUG
    "AUDIT":
      level: ALL
    "gov.ca.cwds":
      level: DEBUG
  appenders:
    - type: console
      threshold: DEBUG
      timeZone: UTC
      target: stdout
      logFormat: '[%X{remoteAddress}] [%date{ISO8601}] [%level] [%thread] [%X{uniqueId}] [%logger:] [%message]%n'